# Generated by Django 5.2.17 on 2026-08-10 09:27

import accounts.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='150 caracteres maximum. Lettres, chiffres et @/./+/-/_ uniquement.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name="nom d'utilisateur")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='prenom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telephone')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name="acces a l'administration")),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='double facteur active')),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='echecs de connexion consecutifs')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name="verrouille jusqu'a")),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['username'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
