# Generated by Django 5.2.17 on 2026-08-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('referentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='referentials.donor', verbose_name='bailleur represente'),
        ),
    ]
