# Generated by Django 5.2.17 on 2026-08-12 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('activite_soumise', 'Activite soumise a validation'), ('activite_validee', 'Activite validee'), ('activite_rejetee', 'Activite rejetee'), ('doublon_detecte', 'Doublon de menage detecte'), ('echeance_proche', 'Echeance bailleur proche'), ('depassement_budget', 'Depassement de ligne budgetaire'), ('indicateur_en_retard', 'Indicateur en retard'), ('compte_modifie', 'Compte ou role modifie')], max_length=30, verbose_name='evenement')),
                ('subject', models.CharField(max_length=200, verbose_name='objet')),
                ('message', models.TextField(verbose_name='message')),
                ('channel', models.CharField(choices=[('application', "Dans l'application"), ('email', 'Par email')], default='application', max_length=15, verbose_name='canal')),
                ('object_type', models.CharField(blank=True, max_length=50, verbose_name="type d'objet")),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name="identifiant de l'objet")),
                ('is_read', models.BooleanField(default=False, verbose_name='lue')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lue le')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='envoyee le')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-sent_at'], name='notificatio_recipie_077e99_idx'), models.Index(fields=['event_type', '-sent_at'], name='notificatio_event_t_7631b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('activite_soumise', 'Activite soumise a validation'), ('activite_validee', 'Activite validee'), ('activite_rejetee', 'Activite rejetee'), ('doublon_detecte', 'Doublon de menage detecte'), ('echeance_proche', 'Echeance bailleur proche'), ('depassement_budget', 'Depassement de ligne budgetaire'), ('indicateur_en_retard', 'Indicateur en retard'), ('compte_modifie', 'Compte ou role modifie')], max_length=30, verbose_name='evenement')),
                ('in_app', models.BooleanField(default=True, verbose_name="dans l'application")),
                ('by_email', models.BooleanField(default=False, verbose_name='par email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'preference de notification',
                'verbose_name_plural': 'preferences de notification',
                'constraints': [models.UniqueConstraint(fields=('user', 'event_type'), name='unique_preference_par_evenement')],
            },
        ),
    ]
