# Generated by Django 5.2.17 on 2026-08-11 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True, verbose_name='code projet')),
                ('title', models.CharField(max_length=200, verbose_name='intitule')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_date', models.DateField(verbose_name='date de debut')),
                ('end_date', models.DateField(verbose_name='date de fin prevue')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_instruction', 'En instruction'), ('approuve', 'Approuve'), ('en_cours', 'En cours'), ('suspendu', 'Suspendu'), ('cloture', 'Cloture'), ('archive', 'Archive')], default='brouillon', max_length=20, verbose_name='statut')),
                ('target_beneficiaries', models.PositiveIntegerField(default=0, verbose_name='beneficiaires vises')),
                ('progress_rate', models.PositiveSmallIntegerField(default=0, verbose_name="taux d'avancement")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='chef de projet')),
                ('sectors', models.ManyToManyField(related_name='projects', to='referentials.sector', verbose_name="secteurs d'intervention")),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('target_population', models.PositiveIntegerField(default=0, verbose_name='population cible')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='referentials.zone', verbose_name='zone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': "site d'intervention",
                'verbose_name_plural': "sites d'intervention",
                'ordering': ['zone__name'],
            },
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('duree', 'Duree'), ('montant', 'Montant'), ('perimetre', 'Perimetre')], max_length=15, verbose_name='type')),
                ('old_value', models.CharField(max_length=255, verbose_name='valeur avant')),
                ('new_value', models.CharField(max_length=255, verbose_name='valeur apres')),
                ('effective_date', models.DateField(verbose_name="date d'effet")),
                ('reason', models.TextField(verbose_name='motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to=settings.AUTH_USER_MODEL, verbose_name='saisi par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'avenant',
                'verbose_name_plural': 'avenants',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.CharField(choices=[('chef', 'Chef de projet'), ('superviseur', 'Superviseur terrain'), ('agent', 'Agent terrain'), ('suivi_evaluation', 'Charge de suivi-evaluation')], max_length=20, verbose_name='role sur le projet')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name="debut d'affectation")),
                ('end_date', models.DateField(blank=True, null=True, verbose_name="fin d'affectation")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project', verbose_name='projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "membre d'equipe",
                'verbose_name_plural': "membres d'equipe",
                'ordering': ['project', 'user'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['manager', 'status'], name='projects_pr_manager_9c148a_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='projet_fin_apres_debut'),
        ),
        migrations.AddConstraint(
            model_name='interventionsite',
            constraint=models.UniqueConstraint(fields=('project', 'zone'), name='unique_site_par_projet'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('project', 'user', 'project_role', 'start_date'), name='unique_affectation'),
        ),
    ]
