# Generated by Django 5.2.17 on 2026-08-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Seuls les projets marques publiables sont exposes sans authentification.', verbose_name='publiable sur le portail'),
        ),
    ]
