# Generated by Django 5.2.17 on 2026-08-12 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0002_trigram'),
        ('projects', '0001_initial'),
        ('referentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='code')),
                ('type', models.CharField(choices=[('formation', 'Formation'), ('sensibilisation', 'Sensibilisation'), ('distribution', 'Distribution'), ('visite', 'Visite de suivi'), ('reunion', 'Reunion communautaire'), ('enquete', 'Enquete')], max_length=20, verbose_name='type')),
                ('activity_date', models.DateField(verbose_name='date de realisation')),
                ('description', models.TextField(verbose_name='description')),
                ('results', models.TextField(blank=True, verbose_name='resultats obtenus')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('gps_accuracy', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='precision GPS (m)')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('synchronisee', 'Synchronisee'), ('soumise', 'Soumise'), ('validee', 'Validee'), ('rejetee', 'Rejetee')], default='brouillon', max_length=15, verbose_name='statut')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='soumise le')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='statuee le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motif de rejet')),
                ('entry_duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='duree de saisie (s)')),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='identifiant client')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creee le')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='agent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project', verbose_name='projet')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_validated', to=settings.AUTH_USER_MODEL, verbose_name='statuee par')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='referentials.zone', verbose_name='localite')),
            ],
            options={
                'verbose_name': 'activite',
                'verbose_name_plural': 'activites',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('males_count', models.PositiveSmallIntegerField(default=0, verbose_name='hommes')),
                ('females_count', models.PositiveSmallIntegerField(default=0, verbose_name='femmes')),
                ('age_breakdown', models.JSONField(blank=True, default=dict, help_text='Cles : 0_5, 6_17, 18_59, 60_plus', verbose_name='ventilation par age')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='activities.activity', verbose_name='activite')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='beneficiaries.household', verbose_name='menage')),
            ],
            options={
                'verbose_name': 'participation',
                'verbose_name_plural': 'participations',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='justificatifs/%Y/%m/', verbose_name='fichier')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='type de fichier')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='legende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='depose le')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activities.activity', verbose_name='activite')),
            ],
            options={
                'verbose_name': 'piece justificative',
                'verbose_name_plural': 'pieces justificatives',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['project', 'status'], name='activities__project_ea6403_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['agent', '-activity_date'], name='activities__agent_i_c006e0_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status', '-created_at'], name='activities__status_cbfc90_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityparticipation',
            constraint=models.UniqueConstraint(fields=('activity', 'household'), name='unique_participation_menage'),
        ),
    ]
