# Generated by Django 5.2.17 on 2026-08-12 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('referentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=150, verbose_name='intitule')),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='Contribution au score de vulnerabilite.', verbose_name='poids')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'critere de vulnerabilite',
                'verbose_name_plural': 'criteres de vulnerabilite',
                'ordering': ['-weight', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='identifiant beneficiaire')),
                ('head_name', models.CharField(max_length=200, verbose_name='nom du chef de menage')),
                ('size', models.PositiveSmallIntegerField(default=1, verbose_name='taille du menage')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('gps_accuracy', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='precision GPS (m)')),
                ('residence_status', models.CharField(choices=[('resident', 'Resident'), ('deplace', 'Deplace interne'), ('refugie', 'Refugie'), ('retourne', 'Retourne')], default='resident', max_length=15, verbose_name='statut de residence')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='enregistre le')),
                ('validation_status', models.CharField(choices=[('a_valider', 'A valider'), ('valide', 'Valide'), ('doublon', 'Doublon confirme')], default='a_valider', max_length=15, verbose_name='statut de validation')),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='identifiant client')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='households_registered', to=settings.AUTH_USER_MODEL, verbose_name='enregistre par')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='households', to='referentials.zone', verbose_name='localite')),
                ('vulnerabilities', models.ManyToManyField(blank=True, related_name='households', to='beneficiaries.vulnerability', verbose_name='vulnerabilites')),
            ],
            options={
                'verbose_name': 'menage',
                'verbose_name_plural': 'menages',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=False, verbose_name='consentement accorde')),
                ('collection_mode', models.CharField(choices=[('ecrit', 'Ecrit'), ('oral', 'Oral'), ('empreinte', 'Empreinte')], max_length=15, verbose_name='mode de recueil')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='recueilli le')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='retire le')),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='beneficiaries.household', verbose_name='menage')),
            ],
            options={
                'verbose_name': 'consentement',
                'verbose_name_plural': 'consentements',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='prenom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, verbose_name='sexe')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('estimated_age', models.PositiveSmallIntegerField(blank=True, help_text='A renseigner lorsque la date de naissance est inconnue.', null=True, verbose_name='age estime')),
                ('relation_to_head', models.CharField(blank=True, max_length=60, verbose_name='lien avec le chef de menage')),
                ('is_head', models.BooleanField(default=False, verbose_name='chef de menage')),
                ('is_enrolled', models.BooleanField(default=False, verbose_name='scolarise')),
                ('has_disability', models.BooleanField(default=False, verbose_name='situation de handicap')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='beneficiaries.household', verbose_name='menage')),
            ],
            options={
                'verbose_name': 'individu',
                'verbose_name_plural': 'individus',
                'ordering': ['-is_head', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='score de proximite')),
                ('status', models.CharField(choices=[('a_arbitrer', 'A arbitrer'), ('confirme', 'Doublon confirme'), ('ecarte', 'Menages distincts')], default='a_arbitrer', max_length=15, verbose_name='statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='arbitre le')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='arbitre par')),
                ('household_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates_as_a', to='beneficiaries.household', verbose_name='menage A')),
                ('household_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates_as_b', to='beneficiaries.household', verbose_name='menage B')),
            ],
            options={
                'verbose_name': 'doublon candidat',
                'verbose_name_plural': 'doublons candidats',
                'ordering': ['-score'],
                'constraints': [models.UniqueConstraint(fields=('household_a', 'household_b'), name='unique_paire_doublon')],
            },
        ),
        migrations.CreateModel(
            name='HouseholdProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='rattache le')),
                ('reach_type', models.CharField(choices=[('atteint', 'Atteint'), ('assiste', 'Assiste')], default='atteint', max_length=10, verbose_name="type d'atteinte")),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='beneficiaries.household', verbose_name='menage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_links', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'rattachement a un projet',
                'verbose_name_plural': 'rattachements aux projets',
                'constraints': [models.UniqueConstraint(fields=('household', 'project'), name='unique_menage_projet')],
            },
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['zone', 'validation_status'], name='beneficiari_zone_id_a2f2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['registered_by', '-registered_at'], name='beneficiari_registe_4510fc_idx'),
        ),
    ]
