# Generated by Django 5.2.17 on 2026-08-10 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Format objet.action, par exemple activite.valider', max_length=100, unique=True, verbose_name='code')),
                ('module', models.CharField(choices=[('securite', 'Securite et administration'), ('projets', 'Projets'), ('financements', 'Financements et budget'), ('beneficiaires', 'Beneficiaires'), ('activites', 'Activites terrain'), ('suivi', 'Suivi-evaluation'), ('restitution', 'Restitution')], max_length=30, verbose_name='module')),
                ('label', models.CharField(max_length=200, verbose_name='intitule')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=100, verbose_name='intitule')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('requires_mfa', models.BooleanField(default=False, verbose_name='second facteur obligatoire')),
                ('users', models.ManyToManyField(blank=True, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='utilisateurs')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Toutes les donnees du systeme'), ('portee', "Limitee a la portee de l'utilisateur")], default='portee', max_length=10, verbose_name='etendue')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='authorization.permission', verbose_name='permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='authorization.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'attribution de permission',
                'verbose_name_plural': 'attributions de permissions',
                'ordering': ['role', 'permission'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='authorization.RolePermission', to='authorization.permission', verbose_name='permissions'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
    ]
