# Generated by Django 5.2.17 on 2026-08-10 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Format objet.action, par exemple activite.valider', max_length=100, unique=True, verbose_name='code')),
                ('module', models.CharField(choices=[('securite', 'Securite et administration'), ('projets', 'Projets'), ('financements', 'Financements et budget'), ('beneficiaires', 'Beneficiaires'), ('activites', 'Activites terrain'), ('suivi', 'Suivi-evaluation'), ('restitution', 'Restitution')], max_length=30, verbose_name='module')),
                ('label', models.CharField(max_length=200, verbose_name='intitule')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=100, verbose_name='intitule')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('requires_mfa', models.BooleanField(default=False, verbose_name='second facteur obligatoire')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='authorization.permission', verbose_name='permissions')),
                ('users', models.ManyToManyField(blank=True, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='utilisateurs')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['label'],
            },
        ),
    ]
