# Generated by Django 5.2.17 on 2026-08-11 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('projects', '0001_initial'),
        ('referentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('global', 'Toutes les donnees'), ('project', 'Un projet'), ('zone', 'Une zone geographique')], max_length=10, verbose_name='type de portee')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='debut de validite')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fin de validite')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='projects.project', verbose_name='projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='referentials.zone', verbose_name='zone')),
            ],
            options={
                'verbose_name': 'portee',
                'verbose_name_plural': 'portees',
                'ordering': ['user', 'scope_type'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', True), ('scope_type', 'global'), ('zone__isnull', True)), models.Q(('project__isnull', False), ('scope_type', 'project'), ('zone__isnull', True)), models.Q(('project__isnull', True), ('scope_type', 'zone'), ('zone__isnull', False)), _connector='OR'), name='portee_coherente')],
            },
        ),
    ]
