# Generated by Django 5.2.17 on 2026-08-12 15:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFrameElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('og', 'Objectif general'), ('os', 'Objectif specifique'), ('resultat', 'Resultat attendu'), ('activite', 'Activite')], max_length=15, verbose_name='niveau')),
                ('code', models.CharField(max_length=30, verbose_name='code')),
                ('title', models.CharField(max_length=300, verbose_name='intitule')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='ordre')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='monitoring.logframeelement', verbose_name='element parent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logframe', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'element de cadre logique',
                'verbose_name_plural': 'cadre logique',
                'ordering': ['project', 'position', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='code')),
                ('title', models.CharField(max_length=300, verbose_name='intitule')),
                ('definition', models.TextField(blank=True, verbose_name='definition')),
                ('unit', models.CharField(choices=[('personnes', 'Personnes'), ('menages', 'Menages'), ('pourcentage', 'Pourcentage'), ('nombre', 'Nombre'), ('seances', 'Seances')], max_length=15, verbose_name='unite')),
                ('baseline', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='valeur de reference')),
                ('target', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valeur cible')),
                ('frequency', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle')], default='trimestrielle', max_length=15, verbose_name='periodicite')),
                ('verification_source', models.CharField(blank=True, max_length=200, verbose_name='source de verification')),
                ('computation_mode', models.CharField(choices=[('calcule', 'Calcule automatiquement'), ('manuel', 'Saisi manuellement')], default='manuel', max_length=10, verbose_name='mode de calcul')),
                ('computation_source', models.CharField(blank=True, choices=[('menages_atteints', 'Menages rattaches au projet'), ('individus_atteints', 'Individus des menages rattaches'), ('activites_validees', 'Activites validees'), ('participants', 'Participants aux activites validees'), ('femmes_atteintes', 'Femmes parmi les individus atteints')], max_length=25, verbose_name='source de calcul')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='monitoring.logframeelement', verbose_name='element mesure')),
            ],
            options={
                'verbose_name': 'indicateur',
                'verbose_name_plural': 'indicateurs',
                'ordering': ['element__position', 'code'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorDisaggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('sexe', 'Sexe'), ('age', "Tranche d'age"), ('zone', 'Zone geographique'), ('vulnerabilite', 'Vulnerabilite')], max_length=15, verbose_name='dimension')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaggregations', to='monitoring.indicator', verbose_name='indicateur')),
            ],
            options={
                'verbose_name': 'desagregation',
                'verbose_name_plural': 'desagregations',
                'constraints': [models.UniqueConstraint(fields=('indicator', 'dimension'), name='unique_desagregation')],
            },
        ),
        migrations.CreateModel(
            name='IndicatorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='debut de periode')),
                ('period_end', models.DateField(verbose_name='fin de periode')),
                ('achieved_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valeur atteinte')),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Valeurs desagregees selon les dimensions declarees.', verbose_name='ventilation')),
                ('comment', models.TextField(blank=True, verbose_name="commentaire d'analyse")),
                ('evidence', models.FileField(blank=True, null=True, upload_to='indicateurs/%Y/', verbose_name='piece justificative')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Valide')], default='brouillon', max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings_entered', to=settings.AUTH_USER_MODEL, verbose_name='saisi par')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.indicator', verbose_name='indicateur')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings_validated', to=settings.AUTH_USER_MODEL, verbose_name='valide par')),
            ],
            options={
                'verbose_name': "releve d'indicateur",
                'verbose_name_plural': "releves d'indicateurs",
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('indicator', 'period_start', 'period_end'), name='unique_releve_par_periode'), models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='periode_coherente'), models.CheckConstraint(condition=models.Q(('achieved_value__gte', 0)), name='valeur_non_negative')],
            },
        ),
        migrations.AddConstraint(
            model_name='logframeelement',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_code_cadre_logique'),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.CheckConstraint(condition=models.Q(('target__gt', 0)), name='cible_positive'),
        ),
    ]
