# Generated by Django 5.2.17 on 2026-08-12 15:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('referentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=60, unique=True, verbose_name='numero de contrat')),
                ('title', models.CharField(max_length=200, verbose_name='intitule')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant accorde')),
                ('signature_date', models.DateField(blank=True, null=True, verbose_name='date de signature')),
                ('eligibility_start', models.DateField(verbose_name="debut d'eligibilite des depenses")),
                ('eligibility_end', models.DateField(verbose_name="fin d'eligibilite des depenses")),
                ('document', models.FileField(blank=True, null=True, upload_to='conventions/%Y/', verbose_name='convention signee')),
                ('status', models.CharField(choices=[('instruction', 'En instruction'), ('signe', 'Signe'), ('clos', 'Clos')], default='instruction', max_length=15, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='referentials.currency', verbose_name='devise')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='referentials.donor', verbose_name='bailleur')),
            ],
            options={
                'verbose_name': 'financement',
                'verbose_name_plural': 'financements',
                'ordering': ['-signature_date', 'contract_number'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='code')),
                ('label', models.CharField(max_length=200, verbose_name='intitule')),
                ('category', models.CharField(choices=[('personnel', 'Personnel'), ('equipement', 'Equipement'), ('activites', 'Activites'), ('transport', 'Transport'), ('fonctionnement', 'Fonctionnement'), ('administratif', 'Frais administratifs')], max_length=20, verbose_name='categorie')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant budgete')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='funding.budgetline', verbose_name='ligne parente')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='funding.grant', verbose_name='financement')),
            ],
            options={
                'verbose_name': 'ligne budgetaire',
                'verbose_name_plural': 'lignes budgetaires',
                'ordering': ['grant', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GrantProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='quote-part (%)')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='funding.grant', verbose_name='financement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_links', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'financement de projet',
                'verbose_name_plural': 'financements de projets',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant')),
                ('expected_date', models.DateField(verbose_name='date prevue')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='date de reception')),
                ('status', models.CharField(choices=[('attendu', 'Attendu'), ('recu', 'Recu'), ('annule', 'Annule')], default='attendu', max_length=10, verbose_name='statut')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='funding.grant', verbose_name='financement')),
            ],
            options={
                'verbose_name': 'tranche de versement',
                'verbose_name_plural': 'tranches de versement',
                'ordering': ['expected_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('narratif', 'Rapport narratif'), ('financier', 'Rapport financier'), ('final', 'Rapport final')], max_length=15, verbose_name='type')),
                ('due_date', models.DateField(verbose_name="date d'echeance")),
                ('status', models.CharField(choices=[('a_faire', 'A faire'), ('en_cours', 'En cours'), ('soumis', 'Soumis'), ('accepte', 'Accepte')], default='a_faire', max_length=10, verbose_name='statut')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='soumis le')),
                ('document', models.FileField(blank=True, null=True, upload_to='rapports-bailleurs/%Y/', verbose_name='document transmis')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='funding.grant', verbose_name='financement')),
            ],
            options={
                'verbose_name': 'echeance de rapportage',
                'verbose_name_plural': 'echeancier de rapportage',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='objet de la depense')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant')),
                ('expense_date', models.DateField(verbose_name='date de la depense')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='depenses/%Y/%m/', verbose_name='piece justificative')),
                ('status', models.CharField(choices=[('saisie', 'Saisie'), ('validee', 'Validee'), ('rejetee', 'Rejetee')], default='saisie', max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creee le')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='funding.budgetline', verbose_name='ligne budgetaire')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='referentials.currency', verbose_name='devise')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_entered', to=settings.AUTH_USER_MODEL, verbose_name='saisie par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='projects.project', verbose_name='projet')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_validated', to=settings.AUTH_USER_MODEL, verbose_name='validee par')),
            ],
            options={
                'verbose_name': 'depense',
                'verbose_name_plural': 'depenses',
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['budget_line', 'status'], name='funding_exp_budget__77b57b_idx'), models.Index(fields=['project', '-expense_date'], name='funding_exp_project_a0516e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='depense_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='grant',
            constraint=models.CheckConstraint(condition=models.Q(('eligibility_end__gt', models.F('eligibility_start'))), name='eligibilite_coherente'),
        ),
        migrations.AddConstraint(
            model_name='grant',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='montant_financement_positif'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('grant', 'code'), name='unique_ligne_par_financement'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('budgeted_amount__gte', 0)), name='montant_ligne_positif'),
        ),
        migrations.AddConstraint(
            model_name='grantproject',
            constraint=models.UniqueConstraint(fields=('grant', 'project'), name='unique_financement_projet'),
        ),
        migrations.AddConstraint(
            model_name='grantproject',
            constraint=models.CheckConstraint(condition=models.Q(('share_percent__gt', 0), ('share_percent__lte', 100)), name='quote_part_valide'),
        ),
    ]
