# Generated by Django 5.2.17 on 2026-08-10 11:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='code ISO')),
                ('name', models.CharField(max_length=60, verbose_name='nom')),
                ('symbol', models.CharField(blank=True, max_length=8, verbose_name='symbole')),
                ('is_base', models.BooleanField(default=False, help_text='Devise dans laquelle les montants sont consolides.', verbose_name='devise de reference')),
            ],
            options={
                'verbose_name': 'devise',
                'verbose_name_plural': 'devises',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='denomination')),
                ('acronym', models.CharField(blank=True, max_length=30, verbose_name='sigle')),
                ('type', models.CharField(choices=[('onu', 'Agence des Nations Unies'), ('bilateral', 'Cooperation bilaterale'), ('ue', 'Union europeenne'), ('fondation', 'Fondation'), ('prive', 'Prive'), ('autre', 'Autre')], max_length=15, verbose_name='type')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='pays')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email de contact')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bailleurs/', verbose_name='logo')),
                ('visibility_rules', models.TextField(blank=True, help_text='Mentions imposees par le bailleur sur les documents produits.', verbose_name='exigences de visibilite')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'bailleur',
                'verbose_name_plural': 'bailleurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='denomination')),
                ('acronym', models.CharField(blank=True, max_length=20, verbose_name='sigle')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='adresse')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telephone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email de contact')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organisation/', verbose_name='logo')),
                ('legal_notice', models.TextField(blank=True, verbose_name='mentions legales')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisation',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=150, verbose_name='intitule')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='referentials.sector', verbose_name='secteur parent')),
            ],
            options={
                'verbose_name': 'secteur',
                'verbose_name_plural': 'secteurs',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='taux')),
                ('effective_date', models.DateField(verbose_name="date d'application")),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_rates', to='referentials.currency', verbose_name='devise de reference')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='referentials.currency', verbose_name='devise')),
            ],
            options={
                'verbose_name': 'taux de change',
                'verbose_name_plural': 'taux de change',
                'ordering': ['-effective_date', 'currency'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'base_currency', 'effective_date'), name='unique_taux_par_date'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='taux_positif')],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('level', models.CharField(choices=[('region', 'Region'), ('prefecture', 'Prefecture'), ('canton', 'Canton'), ('village', 'Village')], max_length=15, verbose_name='niveau')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='referentials.zone', verbose_name='zone parente')),
            ],
            options={
                'verbose_name': 'zone',
                'verbose_name_plural': 'zones',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['level', 'parent'], name='referential_level_62fb44_idx')],
            },
        ),
    ]
