# Generated by Django 5.2.17 on 2026-08-10 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Creation'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation de donnee sensible'), ('export', 'Export de donnees'), ('connexion', 'Connexion'), ('deconnexion', 'Deconnexion'), ('acces_refuse', 'Acces refuse')], max_length=20, verbose_name='action')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name="type d'objet")),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name="identifiant de l'objet")),
                ('object_label', models.CharField(blank=True, max_length=255, verbose_name='designation')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='valeur avant')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='valeur apres')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='navigateur')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='detail')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='horodatage')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
            ],
            options={
                'verbose_name': "entree du journal d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_audit_actor_i_dcd783_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx')],
            },
        ),
    ]
